// Generated by Cursor (Composer).

using Dapper;
using DapperDatabaseHelper.Services;
using Microsoft.Extensions.Logging;
using Moq;
using Moq.Dapper;
using Moq.Protected;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.Common;

namespace DapperDatabaseHelper.UnitTests.Tests.Services;

/// <summary>
///     Generated by Cursor using the Composer model.
/// </summary>
public class GenericDtoStorageTests
{
    private static GenericDtoStorage<WidgetDto, int> StorageFor(IDbConnection connection)
    {
        var factory = new Mock<ISqlConnectionFactory>(MockBehavior.Strict);
        factory.Setup(f => f.GetConnectionAsync()).ReturnsAsync(connection);

        // Logger is only consulted by the Polly retry wrapper; a no-op stand-in is enough here.
        return new GenericDtoStorage<WidgetDto, int>(
            factory.Object,
            new Mock<ILogger<GenericDtoStorage<WidgetDto, int>>>().Object);
    }

    private static Mock<DbConnection> MockDb()
    {
        var db = new Mock<DbConnection>();
        db.SetupAllProperties();
        return db;
    }

    private static DbDataReader AsReader(WidgetDto? row)
    {
        var table = new DataTable();
        table.Columns.Add("Id", typeof(int));
        table.Columns.Add("Name", typeof(string));
        table.Columns.Add("Quantity", typeof(int));
        if (row != null)
        {
            table.Rows.Add(row.Id, row.Name, row.Quantity);
        }

        return table.CreateDataReader();
    }

    // Upsert hits Query* then Execute*; Moq.Dapper's last SetupDapperAsync wins, so we
    // reuse the query-backed command and bolt ExecuteNonQueryAsync onto it.
    private static List<string> AllowLookupThenWrite(Mock<DbConnection> db, Queue<WidgetDto?> lookups)
    {
        var statements = new List<string>();

        db.SetupDapperAsync(c =>
                c.QueryFirstOrDefaultAsync<WidgetDto>(It.IsAny<string>(), It.IsAny<object>(), null, null, null))
            .ReturnsAsync(lookups.Count > 0 ? lookups.Peek()! : null!);

        var cmd = Mock.Get(db.Object.CreateCommand());
        cmd.SetupSet(c => c.CommandText = It.IsAny<string>()).Callback<string>(statements.Add);

        cmd.Protected()
            .Setup<Task<DbDataReader>>("ExecuteDbDataReaderAsync",
                ItExpr.IsAny<CommandBehavior>(), ItExpr.IsAny<CancellationToken>())
            .ReturnsAsync(() => AsReader(lookups.Count > 0 ? lookups.Dequeue() : null));

        cmd.Setup(c => c.ExecuteNonQueryAsync(It.IsAny<CancellationToken>())).ReturnsAsync(1);

        return statements;
    }

    [Fact]
    public async Task DeleteByKeyAsync_IssuesDeleteForKey()
    {
        var db = MockDb();
        db.SetupDapperAsync(c =>
                c.ExecuteAsync(It.IsAny<string>(), It.IsAny<object>(), null, null, null))
            .ReturnsAsync(1);

        // Execute path is registered on IDbConnection.CreateCommand, not CreateDbCommand.
        var command = ((IDbConnection) db.Object).CreateCommand();

        await StorageFor(db.Object).DeleteByKeyAsync(9);

        Assert.Equal("DELETE FROM `widgets` WHERE `Id`=@key\n", command.CommandText);
    }

    [Fact]
    public async Task DeleteByKeyAsync_ReturnsFalseWhenNoRowDeleted()
    {
        var db = MockDb();
        db.SetupDapperAsync(c =>
                c.ExecuteAsync(It.IsAny<string>(), It.IsAny<object>(), null, null, null))
            .ReturnsAsync(0);

        Assert.False(await StorageFor(db.Object).DeleteByKeyAsync(9));
    }

    [Fact]
    public async Task DeleteByKeyAsync_ReturnsTrueWhenOneRowDeleted()
    {
        var db = MockDb();
        db.SetupDapperAsync(c =>
                c.ExecuteAsync(It.IsAny<string>(), It.IsAny<object>(), null, null, null))
            .ReturnsAsync(1);

        var storage = StorageFor(db.Object);

        Assert.True(await storage.DeleteByKeyAsync(9));
    }

    [Fact]
    public async Task GetByKeyAsync_IssuesSelectForKey()
    {
        var expected = new WidgetDto {Id = 7, Name = "beta", Quantity = 1};

        var db = MockDb();
        db.SetupDapperAsync(c =>
                c.QueryFirstOrDefaultAsync<WidgetDto>(It.IsAny<string>(), It.IsAny<object>(), null, null, null))
            .ReturnsAsync(expected);

        // Same DbCommand instance Moq.Dapper will hand to Dapper.
        var command = db.Object.CreateCommand();

        await StorageFor(db.Object).GetByKeyAsync(7);

        Assert.Equal("SELECT * FROM `widgets` WHERE `Id` = @entryId", command.CommandText);
    }

    [Fact]
    public async Task GetByKeyAsync_ReturnsMappedDto()
    {
        var expected = new WidgetDto {Id = 42, Name = "alpha", Quantity = 3};

        var db = MockDb();
        db.SetupDapperAsync(c =>
                c.QueryFirstOrDefaultAsync<WidgetDto>(It.IsAny<string>(), It.IsAny<object>(), null, null, null))
            .ReturnsAsync(expected);

        var result = await StorageFor(db.Object).GetByKeyAsync(42);

        Assert.NotNull(result);
        Assert.Equal(expected.Id, result.Id);
        Assert.Equal(expected.Name, result.Name);
        Assert.Equal(expected.Quantity, result.Quantity);
    }

    [Fact]
    public async Task UpsertAsync_InsertsWhenMissing()
    {
        var dto = new WidgetDto {Id = 1, Name = "gamma", Quantity = 5};

        var db = MockDb();
        var capturedSql = AllowLookupThenWrite(db, new Queue<WidgetDto?>([null]));

        var result = await StorageFor(db.Object).UpsertAsync(dto);

        Assert.Same(dto, result);
        Assert.NotNull(capturedSql);
        var insertSql = Assert.Single(capturedSql,
            sql => sql.StartsWith("INSERT INTO `widgets` (", StringComparison.Ordinal));
        Assert.Contains("`Id`", insertSql);
        Assert.Contains("`widget_name`", insertSql);
        Assert.Contains("`Quantity`", insertSql);
        Assert.Contains("@Id", insertSql);
        Assert.Contains("@widget_name", insertSql);
        Assert.Contains("@Quantity", insertSql);
    }

    [Fact]
    public async Task UpsertAsync_UpdatesWhenExistingAndChanged()
    {
        var existing = new WidgetDto {Id = 2, Name = "old", Quantity = 1};
        var updated = new WidgetDto {Id = 2, Name = "new", Quantity = 1};

        var db = MockDb();
        // Second dequeue is the post-update reload inside UpdateAsync.
        var capturedSql = AllowLookupThenWrite(db, new Queue<WidgetDto?>([existing, updated]));

        var result = await StorageFor(db.Object).UpsertAsync(updated);

        Assert.Equal("new", result.Name);
        Assert.NotNull(capturedSql);
        Assert.Contains("UPDATE `widgets` SET `Name`=@Name\n WHERE `Id`=@key\n", capturedSql);
    }

    [Table("widgets")]
    public sealed class WidgetDto
    {
        [Key]
        public int Id { get; set; }

        [Column("widget_name")]
        public string Name { get; set; } = string.Empty;

        public int Quantity { get; set; }
    }
}